### ISSUE TITLE
Adicionar logger

### ISSUE THREAD

**Issue by jpbretanha** [naveteam/back-boilerplate#20]
Dando uma olhada [nesse artigo](https://www.twilio.com/blog/guide-node-js-logging), adicionar um dos loggers citados.
Temos o [winston](https://github.com/winstonjs/winston) e o [pino](https://getpino.io/#/). Estudar qual o melhor e inserir no projeto

**Comment by bruno-braga** [comment]
A seguir os links que li além do que artigo presente na descrição do issue.
 
1. https://www.youtube.com/watch?v=MDof6xVX-Z0
2. https://www.youtube.com/watch?v=jnriHz6FTEQ
3. https://www.youtube.com/watch?v=DIzJC8wRp-s

Além disso achei interessante que esse pacote que dependendo do caso podemos usar em conjunto com o pino
https://github.com/pinojs/koa-pino-logger#readme

Link para o PR [aqui](https://github.com/naveteam/back-boilerplate/pull/47)
